"""empty message

Revision ID: 2a5162bc0ff4
Revises: f2ed4d23c760
Create Date: 2020-04-01 12:42:12.640661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5162bc0ff4'
down_revision = 'f2ed4d23c760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'date')
    op.drop_column('result', 'rndTesti')
    op.drop_column('result', 'date_modified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('date_modified', sa.DATETIME(), nullable=True))
    op.add_column('result', sa.Column('rndTesti', sa.VARCHAR(length=144), nullable=True))
    op.add_column('result', sa.Column('date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
