"""empty message

Revision ID: 2bfdc7fe7f99
Revises: 9d1852e1e702
Create Date: 2020-04-18 17:27:03.454637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfdc7fe7f99'
down_revision = '9d1852e1e702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_type', sa.VARCHAR(length=144), nullable=True))
    # ### end Alembic commands ###
