"""empty message

Revision ID: 45a127d5e37d
Revises: d95469791af5
Create Date: 2020-03-26 15:54:30.076895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a127d5e37d'
down_revision = 'd95469791af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('password_hash', sa.VARCHAR(length=144), nullable=True))
    # ### end Alembic commands ###
