"""empty message

Revision ID: 51d585330748
Revises: 19093ba3657f
Create Date: 2020-04-02 14:18:03.114411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d585330748'
down_revision = '19093ba3657f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_column('result', 'account_id')
    op.add_column('session', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'account_id')
    op.add_column('result', sa.Column('account_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'result', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###
