"""empty message

Revision ID: 5ddbd34e0b19
Revises: c2543ff6b244
Create Date: 2020-03-30 12:00:44.230090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddbd34e0b19'
down_revision = 'c2543ff6b244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'result', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_column('result', 'account_id')
    # ### end Alembic commands ###
