"""empty message

Revision ID: 6db8f49bce2b
Revises: b8c00e6c4696
Create Date: 2020-04-14 16:29:09.790847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db8f49bce2b'
down_revision = 'b8c00e6c4696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conditioning', 'session', ['workout_id'], ['id'])
    op.drop_column('conditioning', 'time')
    op.drop_column('conditioning', 'workout')
    op.drop_column('conditioning', 'distance')
    op.add_column('result', sa.Column('distance', sa.Integer(), nullable=False))
    op.add_column('result', sa.Column('time', sa.DateTime(), nullable=False))
    op.drop_column('result', 'description')
    op.alter_column('session', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('session', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('result', sa.Column('description', sa.VARCHAR(length=144), nullable=True))
    op.drop_column('result', 'time')
    op.drop_column('result', 'distance')
    op.add_column('conditioning', sa.Column('distance', sa.INTEGER(), nullable=False))
    op.add_column('conditioning', sa.Column('workout', sa.VARCHAR(), nullable=False))
    op.add_column('conditioning', sa.Column('time', sa.DATETIME(), nullable=False))
    op.drop_constraint(None, 'conditioning', type_='foreignkey')
    # ### end Alembic commands ###
