"""empty message

Revision ID: 6fb55c0150f0
Revises: b988b149febe
Create Date: 2020-04-08 11:12:15.098689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb55c0150f0'
down_revision = 'b988b149febe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditioning', 'workout')
    op.drop_column('result', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('description', sa.VARCHAR(length=144), nullable=True))
    op.add_column('conditioning', sa.Column('workout', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
