"""testi

Revision ID: 747c9d6e1c6d
Revises: 
Create Date: 2020-03-25 16:10:51.169786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747c9d6e1c6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('result', sa.Column('rndTesti', sa.String(length=144), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'rndTesti')
    op.drop_column('result', 'date_modified')
    # ### end Alembic commands ###
