"""empty message

Revision ID: 8b408b4eebb3
Revises: 2bfdc7fe7f99
Create Date: 2020-04-18 17:30:26.608571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b408b4eebb3'
down_revision = '2bfdc7fe7f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_type', sa.VARCHAR(length=144), nullable=True))
    # ### end Alembic commands ###
