"""empty message

Revision ID: 94a2bc0c1d08
Revises: 2a5162bc0ff4
Create Date: 2020-04-01 13:01:49.906810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a2bc0c1d08'
down_revision = '2a5162bc0ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'result', 'session', ['session_id'], ['id'])
    op.drop_column('result', 'date')
    op.drop_column('result', 'rndTesti')
    op.drop_column('result', 'date_modified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('date_modified', sa.DATETIME(), nullable=True))
    op.add_column('result', sa.Column('rndTesti', sa.VARCHAR(length=144), nullable=True))
    op.add_column('result', sa.Column('date', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_column('result', 'session_id')
    # ### end Alembic commands ###
