"""empty message

Revision ID: b481aca965e1
Revises: dd5a41b8b0a4
Create Date: 2020-04-06 12:37:23.610671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b481aca965e1'
down_revision = 'dd5a41b8b0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'user_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'user_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    # ### end Alembic commands ###
