"""empty message

Revision ID: b988b149febe
Revises: b481aca965e1
Create Date: 2020-04-08 11:11:15.213449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b988b149febe'
down_revision = 'b481aca965e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('description', sa.VARCHAR(length=144), nullable=True))
    # ### end Alembic commands ###
