"""empty message

Revision ID: dd5a41b8b0a4
Revises: 51d585330748
Create Date: 2020-04-06 12:34:02.895831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5a41b8b0a4'
down_revision = '51d585330748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_type', sa.Enum('user', 'admin'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'user_type')
    # ### end Alembic commands ###
