"""empty message

Revision ID: f2ed4d23c760
Revises: 33940b013f70
Create Date: 2020-03-30 12:05:01.764089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ed4d23c760'
down_revision = '33940b013f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'result', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'result', type_='foreignkey')
    op.drop_column('result', 'account_id')
    # ### end Alembic commands ###
