"""empty message

Revision ID: f78b566e22cc
Revises: 52cf723508e3
Create Date: 2020-04-08 11:15:31.058106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78b566e22cc'
down_revision = '52cf723508e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'description')
    op.alter_column('session', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('session', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('result', sa.Column('description', sa.VARCHAR(length=144), nullable=True))
    # ### end Alembic commands ###
