"""empty message

Revision ID: f9a59963bfd3
Revises: 6b351bdd2a99
Create Date: 2020-04-14 09:34:59.393465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a59963bfd3'
down_revision = '6b351bdd2a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditioning', sa.Column('workout_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'conditioning', 'workout', ['workout_id'], ['id'])
    op.drop_column('conditioning', 'workout')
    op.drop_column('result', 'description')
    op.alter_column('session', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('session', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('result', sa.Column('description', sa.VARCHAR(length=144), nullable=True))
    op.add_column('conditioning', sa.Column('workout', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'conditioning', type_='foreignkey')
    op.drop_column('conditioning', 'workout_id')
    # ### end Alembic commands ###
